### ISSUE TITLE
tcd requirement

### ISSUE THREAD

**Issue by camjac251** [Brisppy/twitch-vod-archiver#1]
I tried to find the tcd binary for downloading twitch chat and could only find https://github.com/acid1103/tcd but it looks like a heavy program that compiles gui elements. Is this the same binary that you use?

**Comment by Brisppy** [comment]
Hi, sorry I somehow I completely missed this.
tcd is actually [Twitch-Chat-Downloader](https://github.com/PetterKraabol/Twitch-Chat-Downloader), and can be installed with pip (pip3 install tcd). I've also added it to the requirements section.
