### ISSUE TITLE
Can't retrive CLIENT_ID and OAUTH_TOKEN:

### ISSUE THREAD

**Issue by MambaBoyy** [Brisppy/twitch-vod-archiver#2]
I can't get CLIENT_ID and OAUTH_TOKEN. I also tried with other browsers but I can't, could the procedure have changed?
![image](https://user-images.githubusercontent.com/84730017/129459248-03f368c6-ce3c-4af0-80f9-9c78d39c2882.png)

**Comment by Brisppy** [comment]
Hmm seems like they've changed something. 
I just tested using the same method but by searching for 'gql.twitch.tv' instead, any of the results there should have those tokens present.
Let me know if that works for you.
