### ISSUE TITLE
The file ".lock" is not created

### ISSUE THREAD

**Issue by MambaBoyy** [Brisppy/twitch-vod-archiver#3]
I'm running the script on linux inside a docker container, all works but the .lock file is not created and found.
Logs:

> DEBUG: Database columns match current version.
INFO: User EnderVaid ID is 172220374.
INFO: All VODs have been grabbed from Twitch.
INFO: Available VODs: [1228653244, 1227697884, 1227697623, 1226794856, 1224981498, 1223875519, 1221952999, 1220167274, 1218447210, 1217448860, 1216420614]
INFO: Channel is currently offline.
INFO: Downloaded VODs: []
INFO: VOD Queue: [1228653244, 1227697884, 1227697623, 1226794856, 1224981498, 1223875519, 1221952999, 1220167274, 1218447210, 1217448860, 1216420614]
INFO: Retrieving VOD: 1228653244
Traceback (most recent call last):
  File "/home/container/twitch-vod-archiver.py", line 452, in <module>
    main()
  File "/home/container/twitch-vod-archiver.py", line 401, in main
    with open(Path(VOD_DIRECTORY, VOD_INFO['user_name'], '.lock.' + str(vod_id)), 'w') as lockfile:
FileNotFoundError: [Errno 2] No such file or directory: 'vod/EnderVaiD/.lock.1228653244'
container@pterodactyl~ Server marked as offline...

**Comment by Brisppy** [comment]
Hi - thanks for taking the time to open an issue.
Could you possibly try [this](https://github.com/Brisppy/twitch-vod-archiver/files/7696128/twitch-vod-archiver.tar.gz) version of the script and let me know if it resolves the issue? You may also need to delete the 'vod/EnderVaiD' directory for this version to recreate the correct directory.

**Comment by Brisppy** [comment]
I've released version 1.3, and I'm 99% sure this should fix the issue you outlined. I'd recommend updating to it as it has a number of other fixes included.
